project_id = "pcfjkrdpdzwcvwupueen"

[api]
url = "https://pcfjkrdpdzwcvwupueen.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZmprcmRwZHp3Y3Z3dXB1ZWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDYyOTgsImV4cCI6MjA2NTkyMjI5OH0.qewakeOsCilrSD18_O9pnev9RQ0K_3wN85UzzbMnMNM"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZmprcmRwZHp3Y3Z3dXB1ZWVuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDM0NjI5OCwiZXhwIjoyMDY1OTIyMjk4fQ.bxAMafBmogAyTGKFUXWySWp2YqR7AQYzfXVoYdZCI7M"
